// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqPUL2ep9zdMxhbNS_Aq45Z6sjCijkUUw',
    appId: '1:406910042016:web:a43e2206cf14ea5c902ec5',
    messagingSenderId: '406910042016',
    projectId: 'tuk-cu-mass-messaging',
    authDomain: 'tuk-cu-mass-messaging.firebaseapp.com',
    storageBucket: 'tuk-cu-mass-messaging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqPUL2ep9zdMxhbNS_Aq45Z6sjCijkUUw',
    appId: '1:406910042016:android:a43e2206cf14ea5c902ec5',
    messagingSenderId: '406910042016',
    projectId: 'tuk-cu-mass-messaging',
    storageBucket: 'tuk-cu-mass-messaging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqPUL2ep9zdMxhbNS_Aq45Z6sjCijkUUw',
    appId: '1:406910042016:ios:a43e2206cf14ea5c902ec5',
    messagingSenderId: '406910042016',
    projectId: 'tuk-cu-mass-messaging',
    storageBucket: 'tuk-cu-mass-messaging.firebasestorage.app',
    iosBundleId: 'com.example.christianUnionAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqPUL2ep9zdMxhbNS_Aq45Z6sjCijkUUw',
    appId: '1:406910042016:ios:a43e2206cf14ea5c902ec5',
    messagingSenderId: '406910042016',
    projectId: 'tuk-cu-mass-messaging',
    storageBucket: 'tuk-cu-mass-messaging.firebasestorage.app',
    iosBundleId: 'com.example.christianUnionAttendanceApp',
  );
}